name: shopfeeforemployee
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.1.1
  dio_cookie_manager: ^3.1.1
  http: ^1.1.0
  flutter_easyloading: ^3.0.5
  get_it: ^7.6.4
  connectivity_plus: ^4.0.2
  dartz: ^0.10.1
  shared_preferences: ^2.2.1
  json_annotation: ^4.6.0
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  lottie: ^2.6.0
  timelines: ^0.1.0
  font_awesome_flutter: ^10.6.0
  permission_handler: ^11.0.1
  custom_refresh_indicator: ^2.2.1
  flutter_native_splash: ^2.3.5
  shimmer: ^3.0.0
  flutter_local_notifications: ^16.1.0
  change_app_package_name: ^1.1.0
  flutter_config: ^2.0.2
  flutter_multi_formatter: ^2.12.4
  image_picker: ^1.0.4
  overlay_tooltip: ^0.2.3
  cached_network_image: ^3.3.0
  page_transition: ^2.1.0
  flutter_slidable: ^3.0.1
  share_plus: ^7.2.2
  url_launcher: ^6.1.5
  bottom_picker: ^2.4.0
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_charts: ^25.1.39+1
  calendar_date_picker2: ^0.5.3
  video_player: ^2.8.5
  speech_to_text: ^6.6.0
#  bluetooth_thermal_printer: ^0.0.6
  bluetooth_print: ^4.3.0
  printing: ^5.12.0
#  Firebase
  firebase_core: ^2.19.0
  firebase_messaging: ^14.7.3
  cloud_firestore: ^4.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  json_serializable: any
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_logo_one.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  background_color: "#000000"

flutter_native_splash:
  background_image: "assets/icons/ic_app.png"
#  image: assets/icons/ic_app.png
#  color: "#000000"
  android_12:
  android_gravity: center
  fullscreen: true
